#!/bin/bash
# Job script to run simple mpi job in parallel on 1 node

# set default resource requirements for job (1 core1 on 1 nodes for 10 seconds)
# - these can be overridden on the qsub command line
#PBS -A ecse1101
#PBS -l select=128
#PBS -l walltime=02:00:00
NPROC=2048
MPISIZE=$NPROC

#Change to directory from which job was submitted
cd $PBS_O_WORKDIR
mkdir -p out

# load openmpi module so that we find the mpirun command
module load use.own
module load pandora-2.0
# module load fftw/3.3.4.1
# module load cray-mpich/7.2.6

# Run executable in parallel over number of node/processors requested
# by the job, output messages go to output_file

# Consider the -N option for parallel processes per node
aprun -n $MPISIZE ../CODE/pandora-2.0/bin/pandora2.0 ip_file.in ./out
